---
- name: Delete clients from HSM
  ansible.builtin.shell: >
    sshpass -p '{{ item.admin_password }}' ssh -o StrictHostKeyChecking=false
    -c aes256-cbc admin@{{ item.hostname }}
    -C "client delete -f -c {{ client_name }}"
  loop: "{{ lunasa_hsms }}"
  ignore_errors: true
  register: ignore_errors_register
